### ISSUE TITLE
Plugin not working in Sublime Text 4

### ISSUE THREAD

**Issue by walkerab** [p3lim/sublime-terrafmt#2]
This started when I upgraded to Sublime Text 4 so I'm assuming it's related.

Now when I save `.tf` files there is no formatting occurring. When I look in the Sublime console I see:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/walker/Library/Application Support/Sublime Text 3/Installed Packages/Terrafmt.sublime-package/terrafmt.py", line 120, in run
  File "/Users/walker/Library/Application Support/Sublime Text 3/Installed Packages/Terrafmt.sublime-package/terrafmt.py", line 44, in format
  File "/Users/walker/Library/Application Support/Sublime Text 3/Installed Packages/Terrafmt.sublime-package/terrafmt.py", line 70, in _exec
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'terraform'
```

Sublime Text Build 4121
macOS 11.6
Apple M1 chip

**Comment by Nothing4You** [comment]
just in case anyone else runs into this, in my case sublime text (on M1 Mac) did not include homebrew's bin in `PATH`, simplest workaround for this is adjusting `cmd` in the package settings to use the absolute path.
